# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/golang/mock
%global goipath         github.com/golang/mock
Version:                1.6.0

%gometa

%global common_description %{expand:
GoMock is a mocking framework for the Go programming language.}

%global golicenses      LICENSE
%global godocs          AUTHORS CONTRIBUTING.md CONTRIBUTORS README.md\\\
                        sample/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        GoMock is a mocking framework for the Go programming language

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in mockgen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck -d github.com/golang/mock/mockgen
%endif

%files
%license LICENSE
%doc AUTHORS CONTRIBUTING.md CONTRIBUTORS README.md sample/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Fri Apr 01 2022 laiot <carmelo.sarta.main@gmail.com> - 1.6.0-1
- Initial package
%autochangelog
%autorelease
