# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/golang/mock
%global goipath         github.com/golang/mock
Version:                1.6.0

%gometa

%global common_description %{expand:
GoMock is a mocking framework for the Go programming language.}

%global golicenses      LICENSE
%global godocs          AUTHORS CONTRIBUTING.md CONTRIBUTORS README.md\\\
                        sample/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        GoMock is a mocking framework for the Go programming language

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}
BuildArch: noarch

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d github.com/golang/mock/mockgen
%endif

%gopkgfiles

%changelog
%autochangelog
